export type RootStackParamList = {
  BusinessDashboard: undefined;
  BusinessBookings: undefined;
  BusinessAnalytics: undefined;
  BusinessSettings: undefined;
  BusinessProfile: undefined;
  ServicesPricing: undefined;
  BusinessHours: undefined;
  AppointmentTypes: undefined;
  CancellationPolicy: undefined;
  BookingRules: undefined;
  PaymentMethods: undefined;
  DepositSettings: undefined;
  VATSettings: undefined;
  PushNotifications: undefined;
  EmailNotifications: undefined;
  SMSNotifications: undefined;
  HelpCentre: undefined;
  ContactSupport: undefined;
  TermsOfService: undefined;
  PrivacyPolicy: undefined;
};
